import { requireOrgUser } from "@/lib/security";
import { db } from "@/lib/prisma";
import { PageHeader } from "@/components/page-header";
import { Activity, CalendarClock, Database, UserRound } from "lucide-react";
import type { CTRole } from "@/lib/ct-access";

export default async function Audit({ ctRole }: { ctRole: CTRole }){
  const u=await requireOrgUser("AUDIT_VIEW");
  const rows=await db.auditLog.findMany({where:{organizationId:u.organizationId!},include:{user:{select:{name:true,email:true}}},orderBy:{createdAt:"desc"},take:300});
  return <div className="space-y-5"><PageHeader ctRole={ctRole} title="Journal d'activité" subtitle="Consultez la traçabilité des opérations sensibles de votre organisation." />
    <section className="grid gap-3 sm:grid-cols-3"><div className="card p-4"><div className="grid size-9 place-items-center rounded-xl bg-cyan-50 text-cyan-600"><Activity size={17}/></div><p className="mt-3 text-xl font-black">{rows.length}</p><p className="text-[10px] text-slate-500">Événements affichés</p></div><div className="card p-4"><div className="grid size-9 place-items-center rounded-xl bg-blue-50 text-blue-600"><UserRound size={17}/></div><p className="mt-3 text-xl font-black">{new Set(rows.map(r=>r.user?.name||"Système")).size}</p><p className="text-[10px] text-slate-500">Acteurs</p></div><div className="card p-4"><div className="grid size-9 place-items-center rounded-xl bg-violet-50 text-violet-600"><Database size={17}/></div><p className="mt-3 text-xl font-black">{new Set(rows.map(r=>r.entity||"—")).size}</p><p className="text-[10px] text-slate-500">Types d'entités</p></div></section>
    <section className="card overflow-hidden"><div className="border-b border-slate-100 p-4"><h2 className="text-sm font-black">Activité récente</h2><p className="text-[10px] text-slate-400">Les 300 derniers événements disponibles.</p></div><div className="overflow-x-auto"><table className="table min-w-[850px]"><thead><tr><th>Date</th><th>Utilisateur</th><th>Action</th><th>Entité</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={4} className="py-10 text-center text-slate-400">Aucune activité enregistrée.</td></tr>:rows.map(r=><tr key={r.id}><td><span className="inline-flex items-center gap-2 text-xs text-slate-500"><CalendarClock size={13}/>{r.createdAt.toLocaleString("fr-FR")}</span></td><td><div><p className="text-xs font-bold text-slate-800">{r.user?.name||"Système"}</p>{r.user?.email&&<p className="text-[9px] text-slate-400">{r.user.email}</p>}</div></td><td><span className="rounded-lg bg-cyan-50 px-2.5 py-1 text-[9px] font-black uppercase tracking-wide text-cyan-700">{r.action}</span></td><td><span className="text-xs text-slate-600">{r.entity||"—"}</span>{r.entityId&&<span className="ml-2 font-mono text-[9px] text-slate-400">#{r.entityId.slice(0,8)}</span>}</td></tr>)}</tbody></table></div></section>
  </div>;
}
