import { notFound } from "next/navigation";
import { requireOrgUser, decrypt } from "@/lib/security";
import { organizationKey } from "@/lib/domain";
import { db } from "@/lib/prisma";
import { fcfa } from "@/lib/money";
import { PaymentForm } from "@/components/payment-form";
import { PrintButton } from "@/components/print-button";
import { ArrowLeft, CheckCircle2, Clock3, FileText, MapPin, Phone } from "lucide-react";

export default async function Receipt({params,backHref}:{params:Promise<{id:string}>;backHref:string}){
 const {id}=await params;const u=await requireOrgUser("ORDERS_VIEW");const [o,org]=await Promise.all([db.order.findFirst({where:{id,organizationId:u.organizationId!},include:{client:true,lines:true,payments:{orderBy:{paidAt:"asc"}}}}),db.organization.findUnique({where:{id:u.organizationId!}})]);if(!o||!org)notFound();
 const key=await organizationKey(org.id);const paid=o.payments.reduce((s,p)=>s+Number(p.amount),0),remaining=Math.max(0,Number(o.total)-paid);const phone=decrypt(org.phoneEncrypted,key),email=decrypt(org.emailEncrypted,key),address=decrypt(org.addressEncrypted,key);const clientPhone=o.client?decrypt(o.client.phoneEncrypted,key):null;
 return <div className="mx-auto max-w-4xl space-y-5"><div className="flex flex-wrap items-center justify-between gap-3 print:hidden"><a href={backHref} className="btn inline-flex items-center gap-2"><ArrowLeft size={15}/>Prestations</a><PrintButton/></div>
 <section className="card overflow-hidden print:border-0 print:shadow-none"><div className="bg-gradient-to-r from-cyan-50 via-white to-blue-50 p-6 md:p-8"><div className="flex flex-wrap justify-between gap-6"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-white px-3 py-1 text-[9px] font-black uppercase tracking-wider text-cyan-700 shadow-sm"><FileText size={12}/>Reçu de prestation</div><h1 className="text-2xl font-black tracking-tight text-slate-950">{org.name}</h1>{address&&<p className="mt-2 flex items-center gap-1.5 text-xs text-slate-500"><MapPin size={13}/>{address}</p>}<p className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500">{phone&&<span className="inline-flex items-center gap-1.5"><Phone size={13}/>{phone}</span>}{email&&<span>{email}</span>}</p></div><div className="text-left sm:text-right"><p className="text-[9px] font-black uppercase tracking-[0.18em] text-slate-400">Référence</p><p className="mt-1 text-lg font-black text-slate-900">{o.ref}</p><p className="mt-1 text-xs text-slate-500">{o.createdAt.toLocaleString("fr-FR")}</p></div></div></div>
 <div className="p-6 md:p-8"><div className="mb-6 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-slate-100 bg-slate-50 p-4"><div><p className="text-[9px] font-black uppercase tracking-wider text-slate-400">Client</p><p className="mt-1 text-sm font-black text-slate-900">{o.client?.name||"Client comptoir"}</p>{clientPhone&&<p className="mt-1 text-xs text-slate-500">{clientPhone}</p>}</div><div className="flex items-center gap-2">{remaining===0?<span className="badge badge-ok inline-flex items-center gap-1.5"><CheckCircle2 size={13}/>Payé</span>:<span className="rounded-full bg-amber-50 px-2.5 py-1 text-[9px] font-black text-amber-700"><Clock3 size={12} className="mr-1 inline"/>Solde restant</span>}</div></div>
 <div className="overflow-x-auto"><table className="table min-w-[600px]"><thead><tr><th>Service</th><th>Qté</th><th>Prix unitaire</th><th>Total</th></tr></thead><tbody>{o.lines.map(l=><tr key={l.id}><td className="font-bold text-slate-800">{l.label}</td><td>{Number(l.quantity)}</td><td>{fcfa(Number(l.unitPrice))}</td><td className="font-black">{fcfa(Number(l.total))}</td></tr>)}</tbody></table></div>
 <div className="mt-7 ml-auto max-w-sm space-y-3 rounded-xl bg-slate-50 p-4"><div className="flex justify-between text-sm"><span className="text-slate-500">Total</span><b>{fcfa(Number(o.total))}</b></div><div className="flex justify-between text-sm"><span className="text-slate-500">Payé</span><b className="text-green-600">{fcfa(paid)}</b></div><div className="flex justify-between border-t border-slate-200 pt-3 text-sm"><span className="font-bold text-slate-700">Reste</span><b className={remaining?"text-amber-600":"text-green-600"}>{fcfa(remaining)}</b></div></div><p className="mt-8 text-center text-xs text-slate-400">Merci pour votre confiance.</p></div></section>
 <div className="card p-5 print:hidden"><PaymentForm orderId={o.id} remaining={remaining}/></div></div>;
}
