"use client";

import { useEffect, useMemo, useState } from "react";
import { Boxes, Link2, PackagePlus, Plus, Search, Settings2, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/page-header";
import { fcfa } from "@/lib/money";

type Service={id:string;name:string;category?:string|null;unit:string;price:number|string;active:boolean};
type Stock={id:string;name:string;unit:string};
type Rule={id:string;serviceName:string;stockItemName:string;qtyPerUnit:number|string;stockUnit:string};
const empty={name:"",category:"Impression",unit:"feuille",price:""};
const emptyRule={serviceId:"",stockItemId:"",qtyPerUnit:"1"};
export default function Services(){
 const [rows,setRows]=useState<Service[]>([]),[stock,setStock]=useState<Stock[]>([]),[rules,setRules]=useState<Rule[]>([]),[f,setF]=useState(empty),[rf,setRf]=useState(emptyRule),[search,setSearch]=useState(""),[saving,setSaving]=useState(false);
 async function load(){try{const [a,b,c]=await Promise.all([fetch("/api/services"),fetch("/api/stock"),fetch("/api/consumption-rules")]);if(!a.ok||!b.ok||!c.ok)throw new Error();const [s,st,r]=await Promise.all([a.json(),b.json(),c.json()]);setRows(Array.isArray(s)?s:[]);setStock(Array.isArray(st)?st:[]);setRules(Array.isArray(r)?r:[])}catch{toast.error("Impossible de charger le catalogue.")}}
 useEffect(()=>{load()},[]);
 async function add(e:React.FormEvent){e.preventDefault();try{setSaving(true);const r=await fetch("/api/services",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...f,name:f.name.trim(),price:Number(f.price)})});if(!r.ok)throw new Error((await r.json().catch(()=>null))?.error||"Impossible de créer le service.");setF(empty);await load();toast.success("Service ajouté.")}catch(e){toast.error(e instanceof Error?e.message:"Une erreur est survenue.")}finally{setSaving(false)}}
 async function addRule(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/consumption-rules",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...rf,qtyPerUnit:Number(rf.qtyPerUnit)})});if(!r.ok)return toast.error((await r.json().catch(()=>null))?.error||"Impossible d'enregistrer la règle.");setRf(emptyRule);await load();toast.success("Règle de consommation enregistrée.")}
 async function delRule(id:string){const r=await fetch(`/api/consumption-rules?id=${id}`,{method:"DELETE"});if(!r.ok)return toast.error("Suppression impossible.");await load();toast.success("Règle supprimée.")}
 const filtered=rows.filter(r=>`${r.name} ${r.category||""}`.toLowerCase().includes(search.toLowerCase().trim()));const active=rows.filter(r=>r.active).length;const average=useMemo(()=>active?rows.filter(r=>r.active).reduce((s,r)=>s+Number(r.price),0)/active:0,[rows,active]);
 return <div className="space-y-5"><PageHeader title="Services" subtitle="Gérez votre catalogue, vos tarifs et la consommation automatique du stock." />
 <section className="grid gap-3 sm:grid-cols-3"><div className="card p-4"><div className="grid size-9 place-items-center rounded-xl bg-cyan-50 text-cyan-600"><Settings2 size={17}/></div><p className="mt-3 text-xl font-black">{rows.length}</p><p className="text-[10px] text-slate-500">Services au catalogue</p></div><div className="card p-4"><div className="grid size-9 place-items-center rounded-xl bg-green-50 text-green-600"><Link2 size={17}/></div><p className="mt-3 text-xl font-black">{rules.length}</p><p className="text-[10px] text-slate-500">Règles de consommation</p></div><div className="card p-4"><div className="grid size-9 place-items-center rounded-xl bg-blue-50 text-blue-600"><PackagePlus size={17}/></div><p className="mt-3 text-xl font-black">{fcfa(average)}</p><p className="text-[10px] text-slate-500">Prix moyen des actifs</p></div></section>
 <form onSubmit={add} className="card overflow-hidden"><div className="flex items-center gap-3 border-b border-slate-100 px-5 py-4"><div className="grid size-9 place-items-center rounded-xl bg-cyan-50 text-cyan-600"><Plus size={17}/></div><div><h2 className="text-sm font-black">Nouveau service</h2><p className="text-[10px] text-slate-400">Ajoutez une prestation vendue par l'imprimerie.</p></div></div><div className="grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-5"><div className="xl:col-span-2"><label className="label">Nom du service <span className="text-red-500">*</span></label><input className="input" placeholder="Ex. Impression couleur A4" value={f.name} onChange={e=>setF({...f,name:e.target.value})} required/></div><div><label className="label">Catégorie</label><input className="input" value={f.category} onChange={e=>setF({...f,category:e.target.value})}/></div><div><label className="label">Unité</label><input className="input" value={f.unit} onChange={e=>setF({...f,unit:e.target.value})}/></div><div><label className="label">Prix <span className="text-red-500">*</span></label><input className="input" type="number" min="0" value={f.price} onChange={e=>setF({...f,price:e.target.value})} required/></div><div className="md:col-span-2 xl:col-span-5 flex justify-end"><button className="btn btn-primary" disabled={saving}>{saving?"Ajout…":"Ajouter le service"}</button></div></div></form>
 <section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-4"><div><h2 className="text-sm font-black">Catalogue</h2><p className="text-[10px] text-slate-400">{filtered.length} service{filtered.length>1?"s":""}</p></div><div className="relative w-full sm:w-64"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="input pl-9" placeholder="Rechercher…" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="overflow-x-auto"><table className="table min-w-[750px]"><thead><tr><th>Service</th><th>Catégorie</th><th>Unité</th><th>Prix</th><th>État</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td className="font-bold text-slate-800">{r.name}</td><td>{r.category||"—"}</td><td>{r.unit}</td><td className="font-black">{fcfa(Number(r.price))}</td><td><span className={r.active?"badge badge-ok":"badge"}>{r.active?"Actif":"Inactif"}</span></td></tr>)}</tbody></table></div></section>
 <div className="pt-2"><PageHeader title="Règles de consommation" subtitle="Associez un service à un consommable pour automatiser la sortie de stock." /></div>
 <form onSubmit={addRule} className="card overflow-hidden"><div className="grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-[1fr_1fr_180px_auto]"><div><label className="label">Service <span className="text-red-500">*</span></label><select className="input" value={rf.serviceId} onChange={e=>setRf({...rf,serviceId:e.target.value})} required><option value="">Choisir un service</option>{rows.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><label className="label">Consommable <span className="text-red-500">*</span></label><select className="input" value={rf.stockItemId} onChange={e=>setRf({...rf,stockItemId:e.target.value})} required><option value="">Choisir un article</option>{stock.map(s=><option key={s.id} value={s.id}>{s.name} ({s.unit})</option>)}</select></div><div><label className="label">Quantité par unité <span className="text-red-500">*</span></label><input className="input" type="number" min="0.001" step="0.001" value={rf.qtyPerUnit} onChange={e=>setRf({...rf,qtyPerUnit:e.target.value})}/></div><button className="btn btn-primary self-end">Enregistrer</button></div></form>
 <section className="card overflow-hidden"><div className="border-b border-slate-100 p-4"><h2 className="text-sm font-black">Règles actives</h2><p className="text-[10px] text-slate-400">Ces règles déterminent la consommation automatique lors d'une prestation.</p></div><div className="overflow-x-auto"><table className="table min-w-[700px]"><thead><tr><th>Service</th><th>Consommable</th><th>Consommation</th><th className="text-right">Action</th></tr></thead><tbody>{rules.length===0?<tr><td colSpan={4} className="py-10 text-center text-slate-400">Aucune règle configurée.</td></tr>:rules.map(r=><tr key={r.id}><td className="font-bold">{r.serviceName}</td><td><span className="inline-flex items-center gap-2"><Boxes size={14} className="text-slate-400"/>{r.stockItemName}</span></td><td>{r.qtyPerUnit} {r.stockUnit}</td><td className="text-right"><button className="btn btn-danger inline-flex items-center gap-1.5" onClick={()=>delRule(r.id)}><Trash2 size={14}/>Supprimer</button></td></tr>)}</tbody></table></div></section>
 </div>;
}
