import { NextResponse } from 'next/server';
import { db } from '@/lib/prisma';
import { requireOrgUser } from '@/lib/security';
import { writeAudit } from '@/lib/domain';

export async function GET(){const u=await requireOrgUser('EXPENSES_VIEW');return NextResponse.json(await db.expense.findMany({where:{organizationId:u.organizationId!},orderBy:{spentAt:'desc'},take:500}));}
export async function POST(req:Request){try{const u=await requireOrgUser('EXPENSES_CREATE');const d=await req.json();const amount=Number(d.amount);if(!d.label?.trim()||!Number.isFinite(amount)||amount<=0)return NextResponse.json({error:'Dépense invalide'},{status:400});const row=await db.expense.create({data:{organizationId:u.organizationId!,label:d.label.trim(),category:d.category?.trim()||'Divers',amount,spentAt:d.spentAt?new Date(d.spentAt):new Date()}});await writeAudit(u.id,u.organizationId,'EXPENSE_CREATED','Expense',row.id,{amount});return NextResponse.json(row);}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Erreur serveur'},{status:e instanceof Error&&e.message==='FORBIDDEN'?403:400});}}
export async function PATCH(req:Request){try{const u=await requireOrgUser('EXPENSES_UPDATE');const d=await req.json();const target=await db.expense.findFirst({where:{id:d.id,organizationId:u.organizationId!}});if(!target)return NextResponse.json({error:'Dépense introuvable'},{status:404});const data:any={};if(d.label!==undefined)data.label=String(d.label).trim();if(d.category!==undefined)data.category=String(d.category).trim()||'Divers';if(d.amount!==undefined){const a=Number(d.amount);if(!Number.isFinite(a)||a<=0)return NextResponse.json({error:'Montant invalide'},{status:400});data.amount=a;}if(d.spentAt!==undefined)data.spentAt=new Date(d.spentAt);const row=await db.expense.update({where:{id:target.id},data});await writeAudit(u.id,u.organizationId,'EXPENSE_UPDATED','Expense',row.id,data);return NextResponse.json({ok:true});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Erreur serveur'},{status:e instanceof Error&&e.message==='FORBIDDEN'?403:400});}}
export async function DELETE(req:Request){try{const u=await requireOrgUser('EXPENSES_UPDATE');const id=new URL(req.url).searchParams.get('id');if(!id)return NextResponse.json({error:'ID requis'},{status:400});const target=await db.expense.findFirst({where:{id,organizationId:u.organizationId!}});if(!target)return NextResponse.json({error:'Dépense introuvable'},{status:404});await db.expense.delete({where:{id}});await writeAudit(u.id,u.organizationId,'EXPENSE_DELETED','Expense',id);return NextResponse.json({ok:true});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Erreur serveur'},{status:e instanceof Error&&e.message==='FORBIDDEN'?403:400});}}
