export const permissions = [
  "DASHBOARD_VIEW","CLIENTS_VIEW","CLIENTS_CREATE","CLIENTS_UPDATE","CLIENTS_DELETE",
  "SERVICES_VIEW","SERVICES_CREATE","SERVICES_UPDATE","SERVICES_DELETE",
  "ORDERS_VIEW","ORDERS_CREATE","ORDERS_UPDATE","ORDERS_CANCEL","PAYMENTS_VIEW","PAYMENTS_CREATE",
  "EXPENSES_VIEW","EXPENSES_CREATE","EXPENSES_UPDATE","STOCK_VIEW","STOCK_CREATE","STOCK_UPDATE","STOCK_ADJUST","STOCK_RESTOCK",
  "EMPLOYEES_VIEW","EMPLOYEES_CREATE","EMPLOYEES_UPDATE","EMPLOYEES_DISABLE","SETTINGS_VIEW","SETTINGS_UPDATE","AUDIT_VIEW"
] as const;
